version: "3.0"
services:
  roncoo-mysql57:
    image: mysql:5.7.27
    container_name: roncoo-mysql
    ports:
      - "3309:3306"
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --default-authentication-plugin=mysql_native_password
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
      - ./db/init-sql:/docker-entrypoint-initdb.d
    networks:
      - roncoo
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: always
  elasticsearch: #服务的名称
    image: daocloud.io/library/elasticsearch:7.7.0         #指定镜像的路径
    restart: always                                        #启动docker，自动运行当前容器
    container_name: elasticsearch                          #容器名称
    ports: #指定多个端口
      - 9200:9200                                          #映射的端口号
      - 9300:9300
    networks:
      - roncoo
    environment:
      - "ES_JAVA_OPTS=-Xms256M -Xmx512M"
      discovery.type: single-node
      - cluster.name=elasticsearch
  #kibana图形化插件
  kibana:
    image: daocloud.io/library/kibana:7.7.0
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_URL: http://10.2.100.2:9200
    ports:
      - "5601:5601"
    networks:
      - roncoo
    depends_on:
      - elasticsearch
  roncoo-redis:
    #定义主机名
    container_name: roncoo-redis
    #使用的镜像；注意这里的版本要与第2步redis版本一致
    image: redis:6.0.6
    #容器的映射端口
    ports:
      - 6379:6379 #注意第二个端口必须是redis.conf中的端口号
    #定义挂载点
    volumes:
      - ./data:/data #挂载/docker-compose/redis/data至容器
      - ./conf/redis.conf:/etc/redis.conf #挂载conf至容器
    networks:
      - roncoo
    privileged: true   #环境变量
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
    #docker 重启后，容器自启动
    restart: always
  app-sba:
    build:
      context: ../roncoo-education-app-sba
      args:
        JAVA_OPTS: '-Xmn128M -Xmx512M'
        RUN_ARGS: '--spring.profiles.active=demo --spring.cloud.nacos.server-addr=10.2.100.2:8848'
    image: roncoo-education-app-sba
    container_name: roncoo-sba
    restart: always
    volumes:
      - ./roncoo/logs/sba:/root/education/logs/sba
    networks:
      - roncoo
    ports:
      - "5721:5721"
    depends_on:
      - elasticsearch
      - roncoo-mysql57
      - roncoo-redis
  app-job:
    build:
      context: ../roncoo-education-app-job
      args:
        JAVA_OPTS: '-Xmn128M -Xmx512M'
        RUN_ARGS: '--spring.profiles.active=demo --spring.cloud.nacos.server-addr=10.2.100.2:8848'
    image: roncoo-education-app-job
    container_name: roncoo-job
    restart: always
    volumes:
      - ./roncoo/logs/job:/root/education/logs/job
    networks:
      - roncoo
    ports:
      - "5820:5820"
    depends_on:
      - elasticsearch
      - roncoo-mysql57
      - roncoo-redis
  app-gateway:
    build:
      context: ../roncoo-education-app-gateway
      args:
        JAVA_OPTS: '-Xmn128M -Xmx512M'
        RUN_ARGS: '--spring.profiles.active=demo --spring.cloud.nacos.server-addr=10.2.100.2:8848'
    image: roncoo-education-app-gateway
    container_name: roncoo-gateway
    restart: always
    volumes:
      - ./roncoo/logs/gateway:/root/education/logs/gateway
    networks:
      - roncoo
    ports:
      - "5840:5840"
    depends_on:
      - elasticsearch
      - roncoo-mysql57
      - roncoo-redis
  system-service:
    build:
      context: ../roncoo-education-system/roncoo-education-system-service
      args:
        JAVA_OPTS: '-Xmn128M -Xmx512M'
        RUN_ARGS: '--spring.profiles.active=demo --spring.cloud.nacos.server-addr=10.2.100.2:8848'
    image: roncoo-education-system-service
    container_name: roncoo-system
    restart: always
    volumes:
      - ./roncoo/logs/system:/root/education/logs/system
    networks:
      - roncoo
    ports:
      - "5730:5730"
    depends_on:
      - elasticsearch
      - roncoo-mysql57
      - roncoo-redis
  user-service:
    build:
      context: ../roncoo-education-user/roncoo-education-user-service
      args:
        JAVA_OPTS: '-Xmn128M -Xmx512M'
        RUN_ARGS: '--spring.profiles.active=demo --spring.cloud.nacos.server-addr=10.2.100.2:8848'
    image: roncoo-education-user-service
    container_name: roncoo-user
    restart: always
    volumes:
      - ./roncoo/logs/user:/root/education/logs/user
    networks:
      - roncoo
    ports:
      - "5720:5720"
    depends_on:
      - elasticsearch
      - roncoo-mysql57
      - roncoo-redis
  course-service:
    build:
      context: ../roncoo-education-course/roncoo-education-course-service
      args:
        JAVA_OPTS: '-Xmn128M -Xmx512M'
        RUN_ARGS: '--spring.profiles.active=demo --spring.cloud.nacos.server-addr=10.2.100.2:8848'
    image: roncoo-education-course-service
    container_name: roncoo-course
    restart: always
    volumes:
      - ./roncoo/logs/course:/root/education/logs/course
    networks:
      - roncoo
    ports:
      - "5710:5710"
    depends_on:
      - elasticsearch
      - roncoo-mysql57
      - roncoo-redis
networks:
  roncoo:
    external: true
